version: 0.2

phases:
  install:
    commands:
      - echo Installing Node...
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt install -y nodejs

  pre_build:
    commands:
      - echo Installing npm depends...
      - npm install

  build:
    commands:
      - echo Building...
      - npm run build

  post_build:
    commands:
      - echo running tests...
      - npm run test

reports:
  jest_reports:
    files:
      - test_report.xml
    base-directory: ./test_reports

artifacts:
  files:
    - "**/*"
    - ../appspec.yml
  discard-paths: no
  base-directory: ./build
